export const LOADING = "TODO/LOADING";
export const FAILURE = "TODo/FAILURE";
export const SHOW_ALERT = "TODO/SHOW_ALERT";
export const HIDE_ALERT = "TODO/HIDE_ALERT";

export const GET_TASKS_SUCCESS = "TODo/GET_TASKS_SUCCESS";

export const GET_TASK_SUCCESS = "TODo/GET_TASK_SUCCESS";

export const ADD_TASK_SUCCESS = "TODo/ADD_TASK_SUCCESS";
export const ADDING_TASK = "TODo/ADDING_TASK";

export const EDIT_TASK_SUCCESS = "TODO/EDIT_TASK_SUCCESS";
export const EDITING_TASK = "TODO/EDITING_TASK";

export const REMOVE_TASK_SUCCESS = "TODO/REMOVE_TASK_SUCCESS";
export const REMOVING_TASK = "TODO/REMOVING_TASK";

export const REMOVE_TASKS_SUCCESS = "TODO/REMOVE_TASKS_SUCCESS";
export const REMOVING_TASKS = "TODO/REMOVING_TASKS";
