export const AUTH_LOADING = "AUTH/AUTH_LOADING";
export const AUTH_FAILURE = "AUTH/AUTH_FAILURE";

export const REGISTER_SUCCESS = "AUTH/REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "AUTH/LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "AUTH/LOGOUT_SUCCESS";
