export const AUTH_LOADING = "AUTH/AUTH_LOADING";
export const AUTH_FAILURE = "AUTH/AUTH_FAILURE";

export const REGISTER_SUCCESS = "AUTH/REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "AUTH/LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "AUTH/LOGOUT_SUCCESS";

export const GET_USER_INFO_SUCCESS = "AUTH/GET_USER_INFO";

export const SEND_MESSAGE_SUCCESS = "AUTH/SEND_MESSAGE";

export const UPDATE_USER_INFO_SUCCESS = "AUTH/UPDATE_USER_INFO";

export const UPDATE_USER_PASSWORD_SUCCESS = "AUTH/UPDATE_USER_PASSWORD";
